### ISSUE TITLE
Two screenshot tools?

### ISSUE THREAD

**Issue by vinzv** [siduction/settings-xfce#2]
We only need one, let's stick with Xfce's default one `xfce-screenshooter`.

![grafik](https://user-images.githubusercontent.com/74432/122617915-7bbecc80-d08d-11eb-9d85-a62e779913d0.png)

**Comment by fethomm** [comment]
Flameshot should stay, as it is much more versatile than most others and is unique in the way it works.

**Comment by vinzv** [comment]
I just did a bit of research and could not find anything on par with Flameshot feature-wise. So, yeah, it should stay. Even it's pulling in quite a few Qt dependencies.

That said, Shutter would be a Gtk alternative but got remove from Debian repos a while ago. It's [ported to Gtk3 meanwhile](https://shutter-project.org/releases/0.96/) so maybe we can revise it for a later release.

**Comment by fethomm** [comment]
For GTK, I guess Shutter is OK. Qt has Spectacle, Flameshot,  Ksnip and more. iirc shutter pulls in mono, which is a dependency we should not lightheartedly invite to the party.

**Comment by vinzv** [comment]
I had the blurry impression as well it was Mono based a while ago. But no traces here: https://packages.debian.org/stretch/shutter

So maybe it's some ancient memory... 🤷‍♂️

**Comment by hhl** [comment]
shutter is in debian again and alive,

apt policy shutter
shutter:
  Installed: (none)
  Candidate: 0.99.2-4

https://shutter-project.org/releases/0.99.4/

So, maybe we can replace flameshot with shutter?

https://packages.debian.org/sid/shutter

**Comment by fethomm** [comment]
Flameshot for the win.

**Comment by vinzv** [comment]
Maybe pick according to dependency count:
- Flameshot for KDE, LXQt
- Shutter for Xfce, (Gnome?)

**Comment by hhl** [comment]
Well, sddm is qt, shutter gtk3+ and perl.

So, how much qt is flameshot pulling in and how much shutter.

But if possible, we should use shutter for gtk.
And as far I remember, shutter was/is like flameshot!

**Comment by vinzv** [comment]
(I would like to switch from SDDM to LightDM for Xfce. But that's another story. ;-))

**Comment by hhl** [comment]
I close it, see

https://github.com/siduction/pyfll/commit/bb226361252ca31bbbe01d4507aae045afca5730

prevent flameshot install on xfce, added shutter as screenshot tool
