### ISSUE TITLE
Revise media player selection

### ISSUE THREAD

**Issue by vinzv** [siduction/settings-xfce#3]
**Currently we have:**
- 2 Video Players (SMPlayer, MPV)
- 1 Music Player (Audacious)
- Youtube browser from SMplayer

**This leaves us with the following:**
1. MPV is technically fine but has no real GUI which makes it hard to use for regular users
2. All three players are Qt based
3. SMplayer is really, really ugly:
![grafik](https://user-images.githubusercontent.com/74432/122617559-c68c1480-d08c-11eb-9a43-e7e29de4e909.png)

## Proposal

- For videos: Celluloid (ex Gnome MPV), a nice modern Gtk frontend for MPV https://celluloid-player.github.io/
![grafik](https://user-images.githubusercontent.com/74432/122618549-bffe9c80-d08e-11eb-8545-bb73d246bd85.png)

- For music: Quod Libet, similar to Rhythmbox or Amarok, has a library feature, lots of preinstalled addons and a tag editor https://github.com/quodlibet/quodlibet
![grafik](https://user-images.githubusercontent.com/74432/122619152-13bdb580-d090-11eb-8404-3ea491859782.png)

**Comment by fethomm** [comment]
I am ok with Quodlibet for music, don't know Celluloid. As long as you don't touch SMPlayer in Plasma, I won't complain. For me personally, it is the best video player out there and in no way ugly.

**Comment by hhl** [comment]
If it is ugly? I think yes by optics and user experience, but in some cases it is the better media-player, even better than VLC (something around 4k and hidpi and high performance graphic-cards!?). Don't know if it spelled right!
We can choose celluloid as default, if wanted, but for sure the most ppl will change to VLC or SM-Player.

**Comment by hhl** [comment]
https://github.com/siduction/pyfll/commit/f78cb0698c8e3359f8f90b17af787ee0f30ff42d

see above
