### ISSUE TITLE
Theme and icon preselection

### ISSUE THREAD

**Issue by vinzv** [siduction/settings-xfce#4]
For having a more consistent Xfce- and Gtk-like look for users I'd use the following:

1. Gtk theme: Greybird-dark
Better support for HiDPI screens via Gtk3
![grafik](https://user-images.githubusercontent.com/74432/122619364-9777a200-d090-11eb-9e00-78ea936590da.png)
2. Icons: Adwaita
Friendly but not intriguing, upstream default.
![grafik](https://user-images.githubusercontent.com/74432/122619493-d9084d00-d090-11eb-81b7-2dbc4167a8f5.png)
3. Window borders: Default
All other themes have too small areas for grabbing the window border which makes them nearly unusable with touchpads
![grafik](https://user-images.githubusercontent.com/74432/122619662-3bf9e400-d091-11eb-900d-b120158b1728.png)

**Comment by fethomm** [comment]
Go with it, Xfce was pretty much unconfigured from our side right from the start, can only get better.

**Comment by hhl** [comment]
greybird-dark is the default theme since c.blues.
adwaita  is the default theme IIRC, but I take a look.

Reminder to  me, remove the verve-plugin from the panel!

Question, is plank really needed? Do we want it? If wanted, we should set it up properly!

**Comment by hhl** [comment]
ToolbarStyle=DEFAULT

    <property name="ThemeName" type="string" value="Greybird-dark"/>
    <property name="IconThemeName" type="string" value="Adwaita"/>

All is long time done, I close it.

If someone thinks it is not, he/she can open it again.
